### ISSUE TITLE
Bit shift direction in AccInit wrong

### ISSUE THREAD

**Issue by I-AM-ENGINEER** [STMicroelectronics/stm32-lsm303agr#1]
I think full description isnt needed for this simple bug:

In 109 line of lsm303agr.c:
`ctrl = (uint8_t) (InitStruct << 8);`

must be replaced by:
`ctrl = (uint8_t) (InitStruct >> 8);`

**Comment by ASEHSTM** [comment]
Hi @I-AM-ENGINEER, 

Thank you for your contribution. You are absolutely right. We will fix the issue soon. 
 
With regards,

**Comment by ASEHSTM** [comment]
ST Internal Reference: 174522
