### ISSUE TITLE
 Question about LSM303AGR_ACC_SENSITIVITY definition in lsm303agr.h

### ISSUE THREAD

**Issue by levietduc0712** [STMicroelectronics/stm32-lsm303agr#4]
Hello STMicroelectronics team,

I've been examining the lsm303agr.h file for the LSM303AGR accelerometer, and I noticed a potential inconsistency in the definition of LSM303AGR_ACC_SENSITIVITY_2G. In the code (line 197), it is defined as ((uint8_t)1), while according to the LSM303AGR datasheet, the linear acceleration sensitivity at ±2 g in normal mode is specified as 3.9mg/LSB.

I would like to understand if this inconsistency is intentional or unintentional. If unintentional, I believe it would be beneficial to add a note in the code or documentation to avoid confusion for users. Clarification on this matter would be greatly appreciated, as it can impact the usage of the accelerometer in various projects.

Thank you for your attention to this matter, and I look forward to your response.

**Comment by TOUNSTM** [comment]
ST Internal Reference: 180190

**Comment by levietduc0712** [comment]
Additionally, upon further examination of the LSM303AGR.c file, I noticed that in line 240, it's noted as "Normal mode." This seems to contradict the explanation provided for the definition LSM303AGR_ACC_SENSITIVITY_2G in lsm303agr.h, which suggests it refers to the high-resolution mode. This inconsistency between the .c and .h files could potentially confuse users who are trying to understand the operating modes and sensitivities of the LSM303AGR accelerometer.

Would it be possible to provide further clarification or possibly update the comments in the code to ensure consistency and clarity for users?

Thank you once again for your assistance.

**Comment by ALABSTM** [comment]
Hi @levietduc0712,

The issue has been forwarded to our development teams. We will get back to you as soon as we get their answer. Thank you for your patience.

With regards,

**Comment by TOUNSTM** [comment]
Fixed in ab801e334530262a8af03821c19827738963b06c
