### ISSUE TITLE
Typo in lsm303agr.h - Incorrect Define Name

### ISSUE THREAD

**Issue by levietduc0712** [STMicroelectronics/stm32-lsm303agr#5]
**Description**
There is a typo in the `lsm303agr.h` file.

**File and Line Number**
The typo is located in `lsm303agr.h` at line 112.

**Current Definition**
```c
#define LSM303AGR_Z_REH_H_M
```

The line should be:
```c
#define LSM303AGR_Z_REG_H_M

**Comment by ASEHSTM** [comment]
ST Internal Reference: 184282

**Comment by KRASTM** [comment]
Fixed in commit https://github.com/STMicroelectronics/stm32-lsm303agr/commit/8431155788077ea6eba08d9ff74ec5dbb1b5f3fb
